const paragraphs = [
  "Keep on walkin' Ain't no stoppin' in this dirty, filthy, rotten Nasty little world we call our home They get blickies poppin' Ain't no option for my partners So they resort to scams and robbin' Take away stress, we ganja-coppin' Blow it all out, it's all forgotten Walkin' with my back against the sun I've been runnin' all my life, that's way before my life begun Since my birth and seconds on Earth, I been the first one to confront All of these cycles that get recycled, makin' it stifle while I stunt Roll me a blunt so I forget it But it make the details look so vivid ",
  "It's tomato or tomato, either way, the boy the greatest Play it, I won't say it no more I was just fucked up, I was just down, down bad I had to tighten the fuck up, but I'm here for the crown Board of Education vs. Brown I was bored of education, left the town Fuck a résumé and fuck a cap and gown Fuck a background check, back 'round when I get the check",
  "She throw it back, hands on her knees I got the racks, so bust the cheeks She love to dance, but not for free So name the price, I'll pay the fee You know that ass want it, I put this cash on it The way you bounce that ass, you make them bitches mad, don't you? You want somebody to come and take care your niece, huh? 'Cause you a bad bitch and you don't fuck with fleas, huh?",
  "Yellow diamonds in the watch, this shit cost a lot Never send a bitch your dot, that's how you get shot I DM in vanish mode, I do that shit a lot Took her panties off and this bitch thicker than the plot All my exes ain't nothin', them hoes busted If my opps ain't rappin', they ass duckin' You ain't ready to pull the trigger, don't clutch it I know you on your period baby, can you suck it?",
  "These bitches love Sosa, O end or no end Fuckin' with them O boys, you gon' get fucked over 'Raris and Rovers, these hoes love Chief Sosa Hit him with that Cobra, now that boy slumped over They do it all for Sosa, you boys ain't making no noise Y'all know I'm a grown boy, your clique full of broke boys God, y'all some broke boys, God, y'all some broke boys We GBE dope boys, we got lots of dough, boy",
  "I got a Draco in my bookbag, lil' bitch Yeah, woo That motherfucker got a kickback on it Yeah, woo That motherfucker got a kickback on it Yeah, woo And I put this on Onyx, I'ma leave my opp in the cement Lay that bitch down in the yard like a picnic He even ain't got no gun, how the fuck he flexin'? We gon' push up, bitch, lil' bitch We gon' push up, bitch, lil' bitch Pull up And I'm takin' shit",
  "This ain't what you want, This ain't what you want Ha! 1600 block, I just wanna rock shake it down I just wanna, ah, ah, ah, ah, ah, ah, ah I just wanna rock, body-ody, yeah shake it down Shawty got that body-ody, ah, ah, ah shake it down Hit her once, no ties shake it-shake it How the fuck you gon' kill my vibe? Shake it down Stand on my money, don't know my size shake it-shake it Pick them sides, and you better choose wisely shake it-shake it down-down That's my high, one, two, three, four, throw up the five shake it-shake it"

];

const spotify = [
    "<iframe style='border-radius:12px' src='https://open.spotify.com/embed/track/1q8DwZtQen5fvyB7cKbShC?utm_source=generator' width='100%' height='152' frameBorder='0' allowfullscreen='' allow='autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture' loading='lazy'></iframe>",
    "<iframe style='border-radius:12px' src='https://open.spotify.com/embed/track/36J0iaPDGbYGsHvYpaYs3k?utm_source=generator' width='100%' height='152' frameBorder='0' allowfullscreen='' allow='autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture' loading='lazy'></iframe>",
    "<iframe style='border-radius:12px' src='https://open.spotify.com/embed/track/27F7BWz4WuC8GuSIcFbx1a?utm_source=generator' width='100%' height='152' frameBorder='0' allowfullscreen='' allow='autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture' loading='lazy'></iframe>",
    "<iframe style='border-radius:12px' src='https://open.spotify.com/embed/track/1bDbXMyjaUIooNwFE9wn0N?utm_source=generator' width='100%' height='152' frameBorder='0' allowfullscreen='' allow='autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture' loading='lazy'></iframe>",
    "<iframe style='border-radius:12px' src='https://open.spotify.com/embed/track/01Lr5YepbgjXAWR9iOEyH1?utm_source=generator' width='100%' height='152' frameBorder='0' allowfullscreen='' allow='autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture' loading='lazy'></iframe>",
    "<iframe style='border-radius:12px' src='https://open.spotify.com/embed/track/3dl8bSF08LQfCf4T6CCksf?utm_source=generator' width='100%' height='152' frameBorder='0' allowfullscreen='' allow='autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture' loading='lazy'></iframe>",
    "<iframe style='border-radius:12px' src='https://open.spotify.com/embed/track/4FyesJzVpA39hbYvcseO2d?utm_source=generator' width='100%' height='152' frameBorder='0' allowfullscreen='' allow='autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture' loading='lazy'></iframe>",
];